### ISSUE TITLE
Dewars nefunguji jako drive 

### ISSUE THREAD

**Issue by radverg** [cemcof/sip#56]
System.ArgumentException: Entity type 'Tube' is defined with a 2-part composite key, but 1 values were passed to the 'Find' method.
         at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.ValidateKeyPropertiesAndExtractCancellationToken(Object[] keyValues, Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues)
         at sip.Dewars.TubesService.UpdateTubeAsync(Tube tube, CancellationToken ct) in /home/emcf/sip/Dewars/TubesService.cs:line 67
         at sip.Dewars.TubesService.UpdateTubeAsync(Tube tube, CancellationToken ct) in /home/emcf/sip/Dewars/TubesService.cs:line 80
         at sip.Dewars.TubeSelector._updateTube() in /home/emcf/sip/Dewars/TubeSelector.razor:line 105
         at sip.Dewars.TubeSelector._okClick() in /home/emcf/sip/Dewars/TubeSelector.razor:line 140
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[2024-08-07 11:37:45] fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'f8U81jwvc5Tj4Kfb7Qbn49oC0a1dudFJMgMnKfjgkJk'.
      System.ArgumentException: Entity type 'Tube' is defined with a 2-part composite key, but 1 values were passed to the 'Find' method.
         at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.ValidateKeyPropertiesAndExtractCancellationToken(Object[] keyValues, Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues)
         at sip.Dewars.TubesService.UpdateTubeAsync(Tube tube, CancellationToken ct) in /home/emcf/sip/Dewars/TubesService.cs:line 67
         at sip.Dewars.TubesService.UpdateTubeAsync(Tube tube, CancellationToken ct) in /home/emcf/sip/Dewars/TubesService.cs:line 80
         at sip.Dewars.TubeSelector._updateTube() in /home/emcf/sip/Dewars/TubeSelector.razor:line 105
         at sip.Dewars.TubeSelector._okClick() in /home/emcf/sip/Dewars/TubeSelector.razor:line 140
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

**Comment by radverg** [comment]
+ nezobrazuji se svg dewarky
